apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof-mysql
  labels:
    app: goof-mysql
spec:
  selector: 
    matchLabels:
      app: goof-mysql
  replicas: 1 
  template:
    metadata:
      labels: 
        app: goof-mysql
    spec:
      containers:
      - image: mysql:5
        imagePullPolicy: Always
        name: goof-msql
        ports:
        - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: root
         - name: MYSQL_DATABASE
           value: acme
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
   - port: 3306
     targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP